export const JSON_OPTIONS = {
  limit: "50mb",
};

export const URL_ENCODE_OPTIONS = { extended: true };

export const STATUS = {
  SUCCESS: 200,
  CREATED: 201,
  NO_CONTENT: 204,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  TIME_OUT: 408,
  TOO_MANY_REQUEST: 429,
  INTERNAL_SERVER_ERROR: 500,
  SERVICE_UNAVAILABLE: 503,
};
